name: ml-fast-deployment-loops
runtime:
  name: python
  options:
    virtualenv: venv
description: Infrastructure for simplifying ML model deployment
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-east-1
